apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.baseUrl }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demowebapp-service
                port:
                  number: 80