apiVersion: v1
kind: Service
metadata:
  name: demowebapp-service
spec:
  selector:
    app: demowebapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 80
      nodePort: 30390